<a href="https://colab.research.google.com/github/siddhipawar645/Python_Numpy_Lib/blob/main/Day13(Q1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np
arr1=np.array([10,20,30,40,50])
print("1D array:",arr1)
print(type(arr1))
arr2=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr2)
print(type(arr2))

1D array: [10 20 30 40 50]
<class 'numpy.ndarray'>
2D array: [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [87]:
import numpy as np
a=np.zeros(8)
print("1D array of 8 zeros:",a)
b=np.ones((4, 4))
print("2D array of shape(4,4):",b)
c=np.zeros((3,3))
print("3*3 Matrix of zeros:",c)

1D array of 8 zeros: [0. 0. 0. 0. 0. 0. 0. 0.]
2D array of shape(4,4): [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3*3 Matrix of zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [90]:
import numpy as np
a=np.arange(0,20,1)
print("Numbers from 0 to 20:",a)
b=np.arange(10,51,2)
print("Even numbers from 10 to 50:",b)
c=np.arange(5,101,5)
print("Number from 5 to 101:",c)

Numbers from 0 to 20: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Even numbers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Number from 5 to 101: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [89]:
import numpy as np
a=np.linspace(0,5,10)
print("10 equally spaced numbers between 0 to 5:",a)
b=np.linspace(-10,10,15)
print("15 equally spaced numbers between -10 t0 10:",b)

10 equally spaced numbers between 0 to 5: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
15 equally spaced numbers between -10 t0 10: [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]


In [91]:
import numpy as np
a=np.random.rand(10)
print("1D array of 10 numbers between 0 and 1:",a)
b=np.random.rand(3,3)
print("3*3 matrix of random numbers from standard normal distribution:",b)
c=np.random.randint(10,51,(4,5))
print("A 2D array (4*5) of random integers:",c)

1D array of 10 numbers between 0 and 1: [0.73579068 0.92745636 0.08770573 0.87365751 0.25055334 0.75407843
 0.38313538 0.42225511 0.765434   0.00985919]
3*3 matrix of random numbers from standard normal distribution: [[0.49859947 0.22124219 0.67854455]
 [0.16522883 0.61332396 0.04794864]
 [0.57143381 0.40297708 0.60189128]]
A 2D array (4*5) of random integers: [[37 45 11 40 10]
 [34 48 12 17 48]
 [39 17 41 11 13]
 [29 14 45 14 23]]


In [92]:
import numpy as np
v1=np.array([2,4,6,8])
v2=np.array([1,3,5,7])
print("Vector v1:",v1)
print("Vector v2:",v2)
v3=v1+v2
print("Addition:",v3)
v3=v1-v2
print("Subtraction:",v3)
v3=v1*v2
print("Multiplication:",v3)
v3=v1/v2
print("Dot product:",v3)

Vector v1: [2 4 6 8]
Vector v2: [1 3 5 7]
Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Multiplication: [ 2 12 30 56]
Dot product: [2.         1.33333333 1.2        1.14285714]


In [93]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("Matrix A:",A)
print("Matrix B:",B)
C=A+B
print("Addition of two matrix:",C)
C=A@B
print("Multiplication of two matrix:",C)
C=A*B
print("Element-wise multilpication:",C)

Matrix A: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B: [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition of two matrix: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication of two matrix: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element-wise multilpication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [95]:
import numpy as np
arr=np.random.randint(1,101,(4,4))
print("Matrix of 4*4:",arr)
print("Shape of matrix:",arr.shape)
print("Dimension of matrix:",arr.ndim)
print("Total numbers of element:",arr.size)
print("Data Type:",type(arr))
print("Mininum value:",arr.min())
print("Maximum value:",arr.max())

Matrix of 4*4: [[58 60 11 32]
 [94 70 90 69]
 [53 99 20 84]
 [62 35 92 43]]
Shape of matrix: (4, 4)
Dimension of matrix: 2
Total numbers of element: 16
Data Type: <class 'numpy.ndarray'>
Mininum value: 11
Maximum value: 99


In [97]:
import numpy as np
arr=np.random.randint(1,51,(20))
print("1D array of 20 random integer(1 to 50):",arr)
arr=arr.reshape(4,5)
print("Reshape it into a 4*5:",arr)
print("Sum:",arr.sum())
print("Mean:",arr.mean())
print("Standard Deviation:",arr.std())
print("Maximum value in each row:",arr.max(axis=1))

1D array of 20 random integer(1 to 50): [ 3 27  8 33 40 31 50 31  7  5  4 39 42 33 14 12 42 24  5 47]
Reshape it into a 4*5: [[ 3 27  8 33 40]
 [31 50 31  7  5]
 [ 4 39 42 33 14]
 [12 42 24  5 47]]
Sum: 497
Mean: 24.85
Standard Deviation: 15.717108512700419
Maximum value in each row: [40 50 42 47]


In [98]:
import numpy as np
try:
    n=int(input("Enter how many random numbers you want to generate: "))
    if n<=0:
        print("Please enter a positive number.")
    else:
        arr=np.random.randint(10, 101, n)
        print("Generated Array:")
        print(arr)
        print("Statistics")
        print("Mean:",np.mean(arr))
        print("Median:",np.median(arr))
        print("Standard Deviation:",np.std(arr))
        print("Minimum:",np.min(arr))
        print("Maximum:",np.max(arr))
        root=int(np.sqrt(n))
        if root*root==n:
            matrix=arr.reshape(root, root)
            print("2D Array:")
            print(matrix)
            print("Row-wise Sum:")
            print(np.sum(matrix, axis=1))
        else:
            print("Cannot reshape into a square 2D array.")
except ValueError:
    print("Invalid input! Please enter an integer...")

Enter how many random numbers you want to generate: 9
Generated Array:
[92 72 88 18 16 16 74 67 79]
Statistics
Mean: 58.0
Median: 72.0
Standard Deviation: 30.107215820205703
Minimum: 16
Maximum: 92
2D Array:
[[92 72 88]
 [18 16 16]
 [74 67 79]]
Row-wise Sum:
[252  50 220]
